<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151111195014 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE moc_greenlog_domain_model_commit (persistence_object_identifier VARCHAR(40) NOT NULL, deployment VARCHAR(40) DEFAULT NULL, sha1 VARCHAR(255) NOT NULL, date DATETIME NOT NULL, author VARCHAR(255) NOT NULL, committer VARCHAR(255) NOT NULL, message VARCHAR(255) NOT NULL, INDEX IDX_CC42BF90EB1255BE (deployment), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE moc_greenlog_domain_model_deployment (persistence_object_identifier VARCHAR(40) NOT NULL, installation VARCHAR(40) DEFAULT NULL, user VARCHAR(255) NOT NULL, deploytime DATETIME NOT NULL, INDEX IDX_312F68951CBA6AB1 (installation), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE moc_greenlog_domain_model_installation (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, remote VARCHAR(255) NOT NULL, hostname VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE moc_greenlog_domain_model_commit ADD CONSTRAINT FK_CC42BF90EB1255BE FOREIGN KEY (deployment) REFERENCES moc_greenlog_domain_model_deployment (persistence_object_identifier)");
		$this->addSql("ALTER TABLE moc_greenlog_domain_model_deployment ADD CONSTRAINT FK_312F68951CBA6AB1 FOREIGN KEY (installation) REFERENCES moc_greenlog_domain_model_installation (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE moc_greenlog_domain_model_commit DROP FOREIGN KEY FK_CC42BF90EB1255BE");
		$this->addSql("ALTER TABLE moc_greenlog_domain_model_deployment DROP FOREIGN KEY FK_312F68951CBA6AB1");
		$this->addSql("DROP TABLE moc_greenlog_domain_model_commit");
		$this->addSql("DROP TABLE moc_greenlog_domain_model_deployment");
		$this->addSql("DROP TABLE moc_greenlog_domain_model_installation");
	}
}