
-
  name: 'api'
  uriPattern: 'register'
  defaults:
    '@package':    'Moc.GreenLogApi'
    '@controller': 'Api'
    '@action':     'registerDeployment'
    '@format':     'json'
  httpMethods:
    - POST

-
  name: 'get script'
  uriPattern: 'go'
  defaults:
    '@package':    'Moc.GreenLogApi'
    '@controller': 'Api'
    '@action':     'getScript'
    '@format':     'txt'

-
  name: 'update script'
  uriPattern: 'update'
  defaults:
    '@package':    'Moc.GreenLogApi'
    '@controller': 'Api'
    '@action':     'updateScript'
